### ISSUE TITLE
Any idea what I can do to fix this error? Are there Linux packages missing?

### ISSUE THREAD

**Issue by PeterKW** [kbrawley95/VSCode-OpenGL-Game-Engine#2]
Any idea what I can do to fix this error? Are there Linux packages missing?
![image](https://user-images.githubusercontent.com/13779157/99911508-cdb49500-2cec-11eb-906d-6e3f9d5d754d.png)

**Comment by kbrawley95** [comment]
Hey - apologies for the delay. This repo has been pretty dormant since it's initial creation as a university aid. I'm not sure which distro of Linux you're developing on, but certain paths may not exist/vary from where you have you source (and lib) files. In which case, you'll have to update them manually. 

This configuration was based on my own local Ubuntu 16.04 environment.
